src/Entity/Category.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\CategoryRepository")
 */
class Category
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name_category;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Product", mappedBy="category")
     */
    private $products;

    public function __construct()
    {
        $this->products = new ArrayCollection();
    }

    public function getId()
    {
        return $this->id;
    }

    public function getNameCategory(): ?string
    {
        return $this->name_category;
    }

    public function setNameCategory(string $name_category): self
    {
        $this->name_category = $name_category;

        return $this;
    }

    /**
     * @return Collection|Product[]
     */
    public function getProducts(): Collection
    {
        return $this->products;
    }

    public function addProduct(Product $product): self
    {
        if (!$this->products->contains($product)) {
            $this->products[] = $product;
            $product->setCategory($this);
        }

        return $this;
    }

    public function removeProduct(Product $product): self
    {
        if ($this->products->contains($product)) {
            $this->products->removeElement($product);
            // set the owning side to null (unless already changed)
            if ($product->getCategory() === $this) {
                $product->setCategory(null);
            }
        }

        return $this;
    }
}

src/Entity/Product.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ProductRepository")
 */
class Product
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name_product;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $text;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Category", inversedBy="products")
     * @ORM\JoinColumn(nullable=false)
     */
    private $category;

    public function getId()
    {
        return $this->id;
    }

    public function getNameProduct(): ?string
    {
        return $this->name_product;
    }

    public function setNameProduct(string $name_product): self
    {
        $this->name_product = $name_product;

        return $this;
    }

    public function getText(): ?string
    {
        return $this->text;
    }

    public function setText(string $text): self
    {
        $this->text = $text;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }
}

templates/Page/addindb.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <nav aria-label="breadcrumb">
        <div class="jumbotron">
            <h1 class="display-4">{{ title }}</h1>
            <p class="lead"></p>
            <hr class="my-4">
            <h2>Таблица продуктов</h2>
        </div>
    </nav>
        <table class="table table-hover">
            <thead>
            <tr>
                <th scope="col">ID</th>
                <th scope="col">Продукт</th>
                <th scope="col">Описание</th>
            </tr>
            </thead>
            <tbody>
            {% for value in db_products_all %}
            <tr>
                <td>{{ value.id }}</td>
                <td>{{ value.nameProduct }}</td>
                <td>{{ value.text }}</td>
            </tr>
            {% endfor %}
            </tbody>
        </table>


{% endblock %}

templates/Page/category.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{ path('app_homepage') }}">Home</a></li>
            <li class="breadcrumb-item active" aria-current="page">{{ category_slug }}</li>
        </ol>
        <div class="jumbotron">
            <h1 class="display-4">{{ category_slug }}</h1>
            <p class="lead"></p>
            <hr class="my-4">
            <h2>Выберите интересующий продукт:</h2>
        </div>
    </nav>

    <div class="container">

                {% for value in db_product %}
                    <a class="dropdown-item" href="{{ category_slug }}/{{ value.name_product }}">{{ value.name_product }}</a><br />
                {% endfor %}

    </div>
{% endblock %}

templates/Page/contacts.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{ path('app_homepage') }}">Home</a></li>
            <li class="breadcrumb-item active" aria-current="page">Contacts</li>
        </ol>
        <div class="jumbotron">
            <h1 class="display-4">Обратная связь</h1>
            <p class="lead">О возникших вопросах и пожелания напишите нам письмо, изложив суть.</p>
            <hr class="my-4">
            <p class="lead">Мы сделаем все, чтобы подобные вопросы больше Вас не беспокоили!
                Чтобы учесть все ваши пожелания и сообщить о проделанной работе по устранению возникших вопросов,
                нам нужно будет связаться с Вами. Сообщите, как Вас зовут и каким способом Вам удобнее ответить – нам
                будет приятно известить Вас о произошедших изменениях.</p>
        </div>
    </nav>
    <div class="container-drop">

        <form class="form_add_product" method="post" action="{{ path('add_product') }}">
            <p>Форма добавления Продуктов:</p>
                    <div class="right_block">
                    <textarea class="form-control" name="text" id="exampleFormControlTextarea1" rows="6" placeholder="Описание продукта" required></textarea>
                    </div>
                    <div class="mb-3" id="left_block">
                        <p>Напишите наименование: </p>
                            <input type="text" name="name_product" class="form-control" id="validationCustom01" placeholder="Наименование продукта" required>
                        <p>Выберите категорию: </p>
                        <select id="sources" class="custom-select sources" placeholder="Source Type" name="category_id">
                            {% for value in db_category %}
                                <option value="{{ value.id}}">{{ value.nameCategory}}</option>
                            {% endfor %}
                        </select>
                    </div>
            <button class="btn btn-primary" type="submit">Добавить</button>
        </form>

        <div class="container-del">
            <form class="form_del_product" method="post" action="{{ path('del_product') }}">
                <p>Форма yдаление Продукта:</p>
                <div class="mb-3" id="middle_block">
                    <p>Выберите продук: </p>
                    <select id="sources" class="custom-select sources" placeholder="Source Type" name="product_id">
                        {% for value in db_product %}
                            <option value="{{ value.id}}">{{ value.nameProduct}}</option>
                        {% endfor %}
                    </select>
                </div>
                <button class="btn btn-primary" type="submit">Удалить</button>
            </form>
        </div>



        <div class="b-container">
            <a href="javascript:PopUpShow('#popup1')"> Написать</a>
        </div>
        <div class="b-popup" id="popup1">
            <div class="b-popup-content">

                <form class="needs-validation" novalidate method="post" action="{{ path('add_feedback') }}">
                    <div class="form-row">
                        <div class="col-md-4 mb-3">
                            <label for="validationCustom01">Фамилия</label>
                            <input type="text" name="Surname" class="form-control" id="validationCustom01" placeholder="Фамилия" required>
                        </div>
                        <div class="col-md-4 mb-3">
                            <label for="validationCustom02">Имя</label>
                            <input type="text" name="Firsname" class="form-control" id="validationCustom02" placeholder="Имя" required>
                        </div>
                        <div class="col-md-4 mb-3">
                            <label for="validationCustomUsername">Электронная почта</label>
                            <div class="input-group">
                                <div class="input-group-prepend">
                                    <span class="input-group-text" id="inputGroupPrepend">@</span>
                                </div>
                                <input type="text" name="email"class="form-control" id="validationCustomUsername" placeholder="Электронная почта" aria-describedby="inputGroupPrepend" required>
                            </div>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group">
                            <label for="exampleFormControlTextarea1">Комментарий</label>
                            <textarea class="form-control" name="question" id="exampleFormControlTextarea1" rows="12" required></textarea>
                        </div>
                    </div>
                    <button class="btn btn-primary" type="submit">Отправить</button>
                </form>
            </div>
        </div>

    </div>




{% endblock %}

templates/Page/homepage.html.twig
{% extends 'base.html.twig' %}

{% block body %}

    <div class="jumbotron">
        <h1 class="display-4">Добро пожаловать!</h1>
        <p class="lead">Приложение было разработана для демонстрации навыков работы на PHP с framework Symfony 4.</p>
        <hr class="my-4">
        <p>Тестовое задание было выполнено Ковалевич Артёмом Юрьевичем</p>
    </div>

        <div class="container">
                <div class="title">
                <h4>Выберите категорию: </h4>
                </div>
            <div class="dropdown">
                <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">

                </a>
                <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                        {% for value in db_category %}
                            <a class="dropdown-item" href="{{ value.nameCategory }}">{{ value.nameCategory }}</a>
                        {% endfor %}
                </div>
            </div>
        </div>

{% endblock %}

templates/Page/message.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <nav aria-label="breadcrumb" id="message">
        <div class="jumbotron">
            <h1 class="display-4">{{ title }}</h1>
            <p class="lead"></p>
            <hr class="my-4">
            <a href="{{ path('app_homepage') }}"><p>Перейки на главную страницу</p></a>
        </div>

{% endblock %}

templates/Page/product.html.twig
{% extends 'base.html.twig' %}

{% block body %}

    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{ path('app_homepage') }}">Home</a></li>
            <li class="breadcrumb-item active" aria-current="page">{{ category_slug }}</li>
        </ol>
        <div class="jumbotron">
            <h1 class="display-4">{{ category_slug }}</h1>
            <p class="lead"></p>
            <hr class="my-4">
            <h2>{{ product_slug }}</h2>
        </div>
    </nav>
    <div class="container">
        <div class="text">
            {% for value in db_product %}
            <h2>{{ value.text }}</h2>
            {% endfor %}
        </div>
    </div>


{% endblock %}